language: ruby
rvm:
  - 2.7
  
env:
  global:
    - travis_internal_ruby=2.7

before_script:
  - sudo apt update -y
  - sudo apt install zip git -y

script:
  - dd if=/dev/zero of=/tmp/testfile bs=1024 count=10240
  
#   - ruby -v

jobs:
  include:
    - env: Power-Focal
      dist: focal # default (xenial) does not work
      arch: ppc64le
      os: linux

before_deploy:
  - cd /home/travis/.rvm/gems/ruby-3.1.2/
  - ls
#   - sudo bundle update

deploy:
  provider: releases
  script: ls /home/travis/.rvm/gems/
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: /tmp/testfile
  skip_cleanup: true
  on:
    branch: deploy
