language: ruby
rvm:
  - 2.7
  
env:
  global:
    - travis_internal_ruby=2.7

before_script:
  - sudo apt update -y
  - sudo apt install zip git -y

script:
  - dd if=/dev/zero of=/tmp/testfile bs=1024 count=10240
  
#   - ruby -v

jobs:
  include:
    - env: Power-Focal
      dist: focal # default (xenial) does not work
      arch: ppc64le
      os: linux

before_deploy:
  - cd /tmp
  - git clone https://github.com/travis-ci/dpl
  - cd dpl
  - git checkout v1.10.16
  - sed -i 's/0.16.0/0.17.3/g' dpl-releases.gemspec
  - gem build dpl-releases.gemspec && cp *.gem "$TRAVIS_BUILD_DIR"

deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file: /tmp/testfile
  edge: local
  skip_cleanup: true
  on:
    branch: deploy
