language: ruby
rvm:
  - 2.7
  
env:
  global:
    - travis_internal_ruby=2.7

before_install:
  - ls /home/travis/.rvm/gems/
  - ls $HOME/.rvm/scripts/rvm
#   - sudo gem update 

# before_script:
# - sudo apt update -y
# - sudo apt install zip git -y

script:
  - gem list
#   - ruby -v

jobs:
  include:
    - env: Power-Focal
      dist: focal # default (xenial) does not work
      arch: ppc64le
      os: linux

# deploy:
#   provider: releases
#   api_key: ${GITHUB_OAUTH_TOKEN}
#   file: /tmp/testfile
#   skip_cleanup: true
#   on:
#     branch: deploy
